/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.managergui;

import java.awt.Component;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author arnavsood
 */
public class Dialogs extends javax.swing.JFrame {
    Database database = new Database("csce315_971_arnav_sood", "arnav_sood");

    /**
     * Creates new form Dialogs
     */
    public boolean isNumber(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public void throwErrorMessage() {
        Errors error = new Errors();
        error.setLocationRelativeTo(null);
        error.setVisible(true);
        error.pack();
        error.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        error.setTitle("ERROR Message");
    }

    public void throwSuccessMessage(int successType) {
        Successes success = new Successes();
        JPanel dialogPanel = success.getSuccessPanel();
        if (successType == 1) {
            dialogPanel = success.getSuccessAddMessagePanel();
        }
        success.switchDialogPanel(dialogPanel);
        success.setLocationRelativeTo(null);
        success.setVisible(true);
        success.pack();
        success.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        success.setTitle("Success Message");
    }

    public Dialogs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layered_pane = new javax.swing.JLayeredPane();
        inventory_add_panel = new javax.swing.JPanel();
        id_label_inventory_add_panel = new javax.swing.JLabel();
        name_label_inventory_add_panel = new javax.swing.JLabel();
        last_restock_date_label_inventory_add_panel = new javax.swing.JLabel();
        amount_remaining_label_inventory_add_panel = new javax.swing.JLabel();
        amount_used_label_inventory_add_panel = new javax.swing.JLabel();
        id_textField_inventory_add_panel = new javax.swing.JTextField();
        last_restock_date_textField_inventory_add_panel = new javax.swing.JTextField();
        name_textField_inventory_add_panel = new javax.swing.JTextField();
        amount_remaing_textField_inventory_add_panel = new javax.swing.JTextField();
        amount_used_textField_inventory_add_panel = new javax.swing.JTextField();
        add_inventory_item_button = new javax.swing.JButton();
        restock_inventory_item_panel = new javax.swing.JPanel();
        last_restock_date_textField = new javax.swing.JTextField();
        last_restock_inventory_amount_restocked_textField = new javax.swing.JTextField();
        last_restock_inventory_date_label = new javax.swing.JLabel();
        last_restock_inventory_amount_label = new javax.swing.JLabel();
        restockInventoryItem_button = new javax.swing.JButton();
        id_restock_inventory_textField = new javax.swing.JTextField();
        id_last_restock_label = new javax.swing.JLabel();
        excess_report_panel = new javax.swing.JPanel();
        time_stamp_label = new javax.swing.JLabel();
        time_stamp_textField = new javax.swing.JTextField();
        submit_time_stamp_button = new javax.swing.JButton();
        menu_add_panel = new javax.swing.JPanel();
        menu_add_id_label = new javax.swing.JLabel();
        id_menu_add_textField = new javax.swing.JTextField();
        menu_add_name_label = new javax.swing.JLabel();
        name_menu_add_textField = new javax.swing.JTextField();
        price_menu_add_label = new javax.swing.JLabel();
        price_menu_add_textField = new javax.swing.JTextField();
        menu_add_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuAddInventoryItemsTable = new javax.swing.JTable();
        sales_report_panel = new javax.swing.JPanel();
        begin_time_stamp_label = new javax.swing.JLabel();
        end_time_stamp_textField = new javax.swing.JTextField();
        submit_time_stamps_button = new javax.swing.JButton();
        end_time_stamp_label = new javax.swing.JLabel();
        begin_time_stamp_textField = new javax.swing.JTextField();
        menu_popularity_report_panel = new javax.swing.JPanel();
        popular_start_time_label = new javax.swing.JLabel();
        popular_end_time_textField = new javax.swing.JTextField();
        submit_time_stamps_popular_button = new javax.swing.JButton();
        popular_end_time_label = new javax.swing.JLabel();
        popular_start_time_textField = new javax.swing.JTextField();
        popular_number_of_items_label = new javax.swing.JLabel();
        popular_number_of_items_textField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        layered_pane.setLayout(new java.awt.CardLayout());

        id_label_inventory_add_panel.setText("id:");

        name_label_inventory_add_panel.setText("name:");

        last_restock_date_label_inventory_add_panel.setText("last_restock_date:");

        amount_remaining_label_inventory_add_panel.setText("amount_remaining:");

        amount_used_label_inventory_add_panel.setText("amount_used:");

        add_inventory_item_button.setText("add inventory item");
        add_inventory_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_inventory_item_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventory_add_panelLayout = new javax.swing.GroupLayout(inventory_add_panel);
        inventory_add_panel.setLayout(inventory_add_panelLayout);
        inventory_add_panelLayout.setHorizontalGroup(
            inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_add_panelLayout.createSequentialGroup()
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventory_add_panelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(last_restock_date_label_inventory_add_panel)
                            .addGroup(inventory_add_panelLayout.createSequentialGroup()
                                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(inventory_add_panelLayout.createSequentialGroup()
                                            .addComponent(amount_remaining_label_inventory_add_panel)
                                            .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inventory_add_panelLayout.createSequentialGroup()
                                            .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(name_label_inventory_add_panel, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(id_label_inventory_add_panel, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(inventory_add_panelLayout.createSequentialGroup()
                                        .addComponent(amount_used_label_inventory_add_panel)
                                        .addGap(63, 63, 63)))
                                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_textField_inventory_add_panel)
                                    .addComponent(name_textField_inventory_add_panel)
                                    .addComponent(last_restock_date_textField_inventory_add_panel)
                                    .addComponent(amount_remaing_textField_inventory_add_panel)
                                    .addComponent(amount_used_textField_inventory_add_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))))
                    .addGroup(inventory_add_panelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(add_inventory_item_button)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        inventory_add_panelLayout.setVerticalGroup(
            inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_add_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_label_inventory_add_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label_inventory_add_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_restock_date_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_restock_date_label_inventory_add_panel))
                .addGap(18, 18, 18)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_remaining_label_inventory_add_panel)
                    .addComponent(amount_remaing_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_used_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_used_label_inventory_add_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(add_inventory_item_button)
                .addGap(34, 34, 34))
        );

        layered_pane.add(inventory_add_panel, "card3");

        last_restock_inventory_date_label.setText("date_restocked:");

        last_restock_inventory_amount_label.setText("amount_restocked:");

        restockInventoryItem_button.setText("restock Inventory Item");
        restockInventoryItem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockInventoryItem_buttonActionPerformed(evt);
            }
        });

        id_last_restock_label.setText("id:");

        javax.swing.GroupLayout restock_inventory_item_panelLayout = new javax.swing.GroupLayout(restock_inventory_item_panel);
        restock_inventory_item_panel.setLayout(restock_inventory_item_panelLayout);
        restock_inventory_item_panelLayout.setHorizontalGroup(
            restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restock_inventory_item_panelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(restockInventoryItem_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restock_inventory_item_panelLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last_restock_inventory_amount_label)
                    .addComponent(last_restock_inventory_date_label)
                    .addComponent(id_last_restock_label))
                .addGap(45, 45, 45)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_restock_inventory_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(last_restock_date_textField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_restock_inventory_amount_restocked_textField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        restock_inventory_item_panelLayout.setVerticalGroup(
            restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restock_inventory_item_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_restock_inventory_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_last_restock_label))
                .addGap(29, 29, 29)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_restock_date_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_restock_inventory_date_label))
                .addGap(18, 18, 18)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_restock_inventory_amount_restocked_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_restock_inventory_amount_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(restockInventoryItem_button)
                .addGap(42, 42, 42))
        );

        layered_pane.add(restock_inventory_item_panel, "card4");

        time_stamp_label.setText("time stamp: (yyyy-MM-dd HH:mm:ss)");

        submit_time_stamp_button.setText("Submit");
        submit_time_stamp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_time_stamp_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout excess_report_panelLayout = new javax.swing.GroupLayout(excess_report_panel);
        excess_report_panel.setLayout(excess_report_panelLayout);
        excess_report_panelLayout.setHorizontalGroup(
            excess_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, excess_report_panelLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(submit_time_stamp_button)
                .addGap(162, 162, 162))
            .addGroup(excess_report_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(excess_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time_stamp_label)
                    .addComponent(time_stamp_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        excess_report_panelLayout.setVerticalGroup(
            excess_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excess_report_panelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(time_stamp_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time_stamp_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(submit_time_stamp_button)
                .addGap(39, 39, 39))
        );

        layered_pane.add(excess_report_panel, "card2");

        menu_add_id_label.setText("id:");

        menu_add_name_label.setText("name:");

        price_menu_add_label.setText("price:");

        menu_add_button.setText("Submit");
        menu_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_buttonActionPerformed(evt);
            }
        });

        menuAddInventoryItemsTable.setModel(new CheckboxTableModel(new Object[] { "Inventory", "Name" }, 0));
        menuAddInventoryItemsTable.getColumnModel().getColumn(0).setCellRenderer(new CheckboxCellRenderer());

        DefaultTableModel model = (DefaultTableModel) menuAddInventoryItemsTable.getModel();

        try {
            ResultSet rs = database.getInventory();
            while (rs.next()) {
                model.addRow(new Object[] { false, rs.getString("name") });
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        jScrollPane1.setViewportView(menuAddInventoryItemsTable);
        if (menuAddInventoryItemsTable.getColumnModel().getColumnCount() > 0) {
            menuAddInventoryItemsTable.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout menu_add_panelLayout = new javax.swing.GroupLayout(menu_add_panel);
        menu_add_panel.setLayout(menu_add_panelLayout);
        menu_add_panelLayout.setHorizontalGroup(
            menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_add_panelLayout.createSequentialGroup()
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_add_panelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(menu_add_button))
                    .addGroup(menu_add_panelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menu_add_panelLayout.createSequentialGroup()
                                .addComponent(menu_add_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menu_add_panelLayout.createSequentialGroup()
                                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price_menu_add_label)
                                    .addComponent(menu_add_name_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        menu_add_panelLayout.setVerticalGroup(
            menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_add_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_add_id_label)
                    .addComponent(id_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_add_name_label)
                    .addComponent(name_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_menu_add_label)
                    .addComponent(price_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_add_button)
                .addGap(34, 34, 34))
        );

        layered_pane.add(menu_add_panel, "card2");

        begin_time_stamp_label.setText("beginning time stamp: (yyyy-MM-dd HH:mm:ss)");

        submit_time_stamps_button.setText("Submit");
        submit_time_stamps_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_time_stamps_buttonActionPerformed(evt);
            }
        });

        end_time_stamp_label.setText("ending time stamp: (yyyy-MM-dd HH:mm:ss)");

        javax.swing.GroupLayout sales_report_panelLayout = new javax.swing.GroupLayout(sales_report_panel);
        sales_report_panel.setLayout(sales_report_panelLayout);
        sales_report_panelLayout.setHorizontalGroup(
            sales_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sales_report_panelLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(submit_time_stamps_button)
                .addGap(162, 162, 162))
            .addGroup(sales_report_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(sales_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(begin_time_stamp_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end_time_stamp_label)
                    .addComponent(begin_time_stamp_label)
                    .addComponent(end_time_stamp_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sales_report_panelLayout.setVerticalGroup(
            sales_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_report_panelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(begin_time_stamp_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(begin_time_stamp_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(end_time_stamp_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(end_time_stamp_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(submit_time_stamps_button)
                .addGap(39, 39, 39))
        );

        layered_pane.add(sales_report_panel, "card2");

        popular_start_time_label.setText("beginning time stamp: (yyyy-MM-dd HH:mm:ss)");

        submit_time_stamps_popular_button.setText("Submit");
        submit_time_stamps_popular_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_time_stamps_popular_buttonActionPerformed(evt);
            }
        });

        popular_end_time_label.setText("ending time stamp: (yyyy-MM-dd HH:mm:ss)");

        popular_number_of_items_label.setText("number of items");

        javax.swing.GroupLayout menu_popularity_report_panelLayout = new javax.swing.GroupLayout(menu_popularity_report_panel);
        menu_popularity_report_panel.setLayout(menu_popularity_report_panelLayout);
        menu_popularity_report_panelLayout.setHorizontalGroup(
            menu_popularity_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_popularity_report_panelLayout.createSequentialGroup()
                .addGroup(menu_popularity_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_popularity_report_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(menu_popularity_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(popular_number_of_items_label)
                            .addComponent(popular_start_time_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(popular_end_time_label)
                            .addComponent(popular_start_time_label)
                            .addComponent(popular_end_time_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(popular_number_of_items_textField)))
                    .addGroup(menu_popularity_report_panelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(submit_time_stamps_popular_button)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        menu_popularity_report_panelLayout.setVerticalGroup(
            menu_popularity_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_popularity_report_panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(popular_start_time_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popular_start_time_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popular_end_time_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popular_end_time_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popular_number_of_items_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popular_number_of_items_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(submit_time_stamps_popular_button)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        layered_pane.add(menu_popularity_report_panel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layered_pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layered_pane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menu_add_buttonActionPerformed
        // TODO add your handling code here:
        // get inventory items from check boxes in table
        ArrayList<Integer> inventory_items = new ArrayList<Integer>();
        for (int i = 0; i < menuAddInventoryItemsTable.getRowCount(); i++) {
            if ((boolean) menuAddInventoryItemsTable.getValueAt(i, 0)) {
                try {
                    ResultSet rs = database.getInventory();
                    while (rs.next()) {
                        if (rs.getString("name").equals(menuAddInventoryItemsTable.getValueAt(i, 1))) {
                            inventory_items.add(rs.getInt("id"));
                        }
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
        if (!isNumber(id_menu_add_textField.getText()) || (name_menu_add_textField.getText().isBlank())
                || !isNumber(price_menu_add_textField.getText())) {
            throwErrorMessage();
        } else {
            if (database.addMenuItem(Integer.parseInt(id_menu_add_textField.getText()),
                    name_menu_add_textField.getText(), Double.parseDouble(price_menu_add_textField.getText()))
                    && database.updateMenuItemInventoryItems(Integer.parseInt(id_menu_add_textField.getText()), inventory_items)) {
                throwSuccessMessage(1);
                id_menu_add_textField.setText("");
                name_menu_add_textField.setText("");
                price_menu_add_textField.setText("");

            } else {
                throwErrorMessage();
            }
        }
    }// GEN-LAST:event_menu_add_buttonActionPerformed

    private void add_inventory_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_add_inventory_item_buttonActionPerformed
        // TODO add your handling code here:
        if (!isNumber(id_textField_inventory_add_panel.getText())
                || (last_restock_date_textField_inventory_add_panel.getText().isBlank())
                || !isNumber(amount_remaing_textField_inventory_add_panel.getText())
                || (name_textField_inventory_add_panel.getText().isBlank())
                || !isNumber(amount_used_textField_inventory_add_panel.getText())) {
            throwErrorMessage();
        } else {
            if (database.addInventoryItem(Integer.parseInt(id_textField_inventory_add_panel.getText()),
                    name_textField_inventory_add_panel.getText(),
                    last_restock_date_textField_inventory_add_panel.getText(),
                    Integer.parseInt(amount_remaing_textField_inventory_add_panel.getText()),
                    Integer.parseInt(amount_used_textField_inventory_add_panel.getText()))) {
                throwSuccessMessage(1);
                id_textField_inventory_add_panel.setText("");
                name_textField_inventory_add_panel.setText("");
                last_restock_date_textField_inventory_add_panel.setText("");
                amount_remaing_textField_inventory_add_panel.setText("");
                amount_used_textField_inventory_add_panel.setText("");

            } else {
                throwErrorMessage();
            }
        }
    }// GEN-LAST:event_add_inventory_item_buttonActionPerformed

    private void restockInventoryItem_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_restockInventoryItem_buttonActionPerformed
        // TODO add your handling code here:
        if (database.restockInventoryItem(Integer.parseInt(id_restock_inventory_textField.getText()),
                last_restock_date_textField.getText(),
                Integer.parseInt(last_restock_inventory_amount_restocked_textField.getText()))) {
            throwSuccessMessage(1);
            id_restock_inventory_textField.setText("");
            last_restock_date_textField.setText("");
            last_restock_inventory_amount_restocked_textField.setText("");

        } else {
            throwErrorMessage();
        }
    }// GEN-LAST:event_restockInventoryItem_buttonActionPerformed

    private void submit_time_stamp_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submit_time_stamp_buttonActionPerformed
        // TODO add your handling code here:
        ArrayList<ArrayList<String>> excess_report_data = database.excessReport(time_stamp_textField.getText());
        if (time_stamp_textField.getText().isBlank() || excess_report_data.isEmpty()) {
            throwErrorMessage();
        } else {
            ExcessReport excess_report = new ExcessReport(excess_report_data);
            excess_report.setLocationRelativeTo(null);
            excess_report.setVisible(true);
            excess_report.pack();
            excess_report.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            excess_report.setTitle("Excess Report");
        }
        
    }//GEN-LAST:event_submit_time_stamp_buttonActionPerformed

    private void submit_time_stamps_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_time_stamps_buttonActionPerformed
        // TODO add your handling code here:
        HashMap<Integer,ArrayList<ArrayList<String>>> sales_report_data = database.salesReport(begin_time_stamp_textField.getText(),end_time_stamp_textField.getText());
        if(begin_time_stamp_textField.getText().isBlank() || end_time_stamp_textField.getText().isBlank() ||sales_report_data.isEmpty() || end_time_stamp_textField.getText().length() != 19 || begin_time_stamp_textField.getText().length() != 19){
            throwErrorMessage();
        }else{
            SalesReport sales_report = new SalesReport(sales_report_data);
            sales_report.setLocationRelativeTo(null);
            sales_report.setVisible(true);
            sales_report.pack();
            sales_report.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sales_report.setTitle("Sales Report");
        }
    }//GEN-LAST:event_submit_time_stamps_buttonActionPerformed

    private void submit_time_stamps_popular_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_time_stamps_popular_buttonActionPerformed
        // TODO add your handling code here:
        ResultSet menu_popular_items_data = database.menuItemsPopularity(popular_start_time_textField.getText(),popular_end_time_textField.getText(),Integer.parseInt(popular_number_of_items_textField.getText()));
        if(popular_end_time_textField.getText().isBlank() || popular_start_time_textField.getText().isBlank() || popular_start_time_textField.getText().length() != 19 || popular_end_time_textField.getText().length() != 19){
            throwErrorMessage();
        }else{
            MenuPopularityReport menu_pop_report = new MenuPopularityReport(menu_popular_items_data);
            menu_pop_report.setLocationRelativeTo(null);
            menu_pop_report.setVisible(true);
            menu_pop_report.pack();
            menu_pop_report.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            menu_pop_report.setTitle("Menu Popularity Report");
        }
    }//GEN-LAST:event_submit_time_stamps_popular_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new Dialogs().setVisible(true);
    // }
    // });
    // }
    public void switchDialogPanel(JPanel panel) {
        layered_pane.removeAll();
        layered_pane.add(panel);
        layered_pane.repaint();
        layered_pane.revalidate();
    }

    public JPanel getInventoryAddPanel() {
        return inventory_add_panel;
    }

    public JPanel getMenuAddPanel() {
        return menu_add_panel;
    }

    public JPanel getRestockInventoryItemPanel() {
        return restock_inventory_item_panel;
    }

    public JPanel getExcessReportPanel() {
        return excess_report_panel;
    }
    public JPanel getSalesReportPanel() {
        return sales_report_panel;
    }
    public JPanel getMenuPopularityReportPanel() {
        return menu_popularity_report_panel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_inventory_item_button;
    private javax.swing.JTextField amount_remaing_textField_inventory_add_panel;
    private javax.swing.JLabel amount_remaining_label_inventory_add_panel;
    private javax.swing.JLabel amount_used_label_inventory_add_panel;
    private javax.swing.JTextField amount_used_textField_inventory_add_panel;
    private javax.swing.JLabel begin_time_stamp_label;
    private javax.swing.JTextField begin_time_stamp_textField;
    private javax.swing.JLabel end_time_stamp_label;
    private javax.swing.JTextField end_time_stamp_textField;
    private javax.swing.JPanel excess_report_panel;
    private javax.swing.JLabel id_label_inventory_add_panel;
    private javax.swing.JLabel id_last_restock_label;
    private javax.swing.JTextField id_menu_add_textField;
    private javax.swing.JTextField id_restock_inventory_textField;
    private javax.swing.JTextField id_textField_inventory_add_panel;
    private javax.swing.JPanel inventory_add_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel last_restock_date_label_inventory_add_panel;
    private javax.swing.JTextField last_restock_date_textField;
    private javax.swing.JTextField last_restock_date_textField_inventory_add_panel;
    private javax.swing.JLabel last_restock_inventory_amount_label;
    private javax.swing.JTextField last_restock_inventory_amount_restocked_textField;
    private javax.swing.JLabel last_restock_inventory_date_label;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JTable menuAddInventoryItemsTable;
    private javax.swing.JButton menu_add_button;
    private javax.swing.JLabel menu_add_id_label;
    private javax.swing.JLabel menu_add_name_label;
    private javax.swing.JPanel menu_add_panel;
    private javax.swing.JPanel menu_popularity_report_panel;
    private javax.swing.JLabel name_label_inventory_add_panel;
    private javax.swing.JTextField name_menu_add_textField;
    private javax.swing.JTextField name_textField_inventory_add_panel;
    private javax.swing.JLabel popular_end_time_label;
    private javax.swing.JTextField popular_end_time_textField;
    private javax.swing.JLabel popular_number_of_items_label;
    private javax.swing.JTextField popular_number_of_items_textField;
    private javax.swing.JLabel popular_start_time_label;
    private javax.swing.JTextField popular_start_time_textField;
    private javax.swing.JLabel price_menu_add_label;
    private javax.swing.JTextField price_menu_add_textField;
    private javax.swing.JButton restockInventoryItem_button;
    private javax.swing.JPanel restock_inventory_item_panel;
    private javax.swing.JPanel sales_report_panel;
    private javax.swing.JButton submit_time_stamp_button;
    private javax.swing.JButton submit_time_stamps_button;
    private javax.swing.JButton submit_time_stamps_popular_button;
    private javax.swing.JLabel time_stamp_label;
    private javax.swing.JTextField time_stamp_textField;
    // End of variables declaration//GEN-END:variables
}

class CheckboxTableModel extends DefaultTableModel {
    public CheckboxTableModel(Object[] columnNames, int rowCount) {
        super(columnNames, rowCount);
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
        if (columnIndex == 0) { // Assuming the checkbox column is the first column
            return Boolean.class;
        }
        return super.getColumnClass(columnIndex);
    }

    @Override
    public boolean isCellEditable(int row, int column) {
        return column == 0; // Make the checkbox column editable
    }
}

class CheckboxCellRenderer extends DefaultTableCellRenderer {
    private static final long serialVersionUID = 1L;

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
            int row, int column) {
        if (value instanceof Boolean) {
            JCheckBox checkbox = new JCheckBox();
            checkbox.setSelected((Boolean) value);
            checkbox.setHorizontalAlignment(JCheckBox.CENTER);
            return checkbox;
        }
        return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
    }

    @Override
    public void setValue(Object value) {
        super.setValue(value);
    }
}