/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.managergui;

import javax.swing.*;

/**
 *
 * @author arnavsood
 */
public class Dialogs extends javax.swing.JFrame {
    Database database = new Database("csce315_971_arnav_sood", "arnav_sood");
    /**
     * Creates new form Dialogs
     */
    public boolean isNumber(String str) {
    try {
        Double.parseDouble(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
    }
    
    public void throwErrorMessage(){
        Errors error = new Errors();
        error.setLocationRelativeTo(null);
        error.setVisible(true);
        error.pack();
        error.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        error.setTitle("ERROR Message");
    }
    public void throwSuccessMessage(int successType){
        Successes success = new Successes();
        JPanel dialogPanel = success.getSuccessPanel();
        if (successType == 1){
            dialogPanel = success.getSuccessAddMessagePanel();
        }
        success.switchDialogPanel(dialogPanel);
        success.setLocationRelativeTo(null);
        success.setVisible(true);
        success.pack();
        success.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        success.setTitle("Success Message");
    }
    
    public Dialogs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layered_pane = new javax.swing.JLayeredPane();
        menu_add_panel = new javax.swing.JPanel();
        menu_add_id_label = new javax.swing.JLabel();
        id_menu_add_textField = new javax.swing.JTextField();
        menu_add_name_label = new javax.swing.JLabel();
        name_menu_add_textField = new javax.swing.JTextField();
        price_menu_add_label = new javax.swing.JLabel();
        price_menu_add_textField = new javax.swing.JTextField();
        menu_add_button = new javax.swing.JButton();
        inventory_add_panel = new javax.swing.JPanel();
        id_label_inventory_add_panel = new javax.swing.JLabel();
        name_label_inventory_add_panel = new javax.swing.JLabel();
        last_restock_date_label_inventory_add_panel = new javax.swing.JLabel();
        amount_remaining_label_inventory_add_panel = new javax.swing.JLabel();
        amount_used_label_inventory_add_panel = new javax.swing.JLabel();
        id_textField_inventory_add_panel = new javax.swing.JTextField();
        last_restock_date_textField_inventory_add_panel = new javax.swing.JTextField();
        name_textField_inventory_add_panel = new javax.swing.JTextField();
        amount_remaing_textField_inventory_add_panel = new javax.swing.JTextField();
        amount_used_textField_inventory_add_panel = new javax.swing.JTextField();
        add_inventory_item_button = new javax.swing.JButton();
        restock_inventory_item_panel = new javax.swing.JPanel();
        last_restock_date_textField = new javax.swing.JTextField();
        last_restock_inventory_amount_restocked_textField = new javax.swing.JTextField();
        last_restock_inventory_date_label = new javax.swing.JLabel();
        last_restock_inventory_amount_label = new javax.swing.JLabel();
        restockInventoryItem_button = new javax.swing.JButton();
        id_restock_inventory_textField = new javax.swing.JTextField();
        id_last_restock_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        layered_pane.setLayout(new java.awt.CardLayout());

        menu_add_id_label.setText("id:");

        menu_add_name_label.setText("name:");

        price_menu_add_label.setText("price:");

        menu_add_button.setText("Submit");
        menu_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_add_panelLayout = new javax.swing.GroupLayout(menu_add_panel);
        menu_add_panel.setLayout(menu_add_panelLayout);
        menu_add_panelLayout.setHorizontalGroup(
            menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_add_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menu_add_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price_menu_add_label)
                    .addComponent(menu_add_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_add_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_add_button)
                .addGap(162, 162, 162))
        );
        menu_add_panelLayout.setVerticalGroup(
            menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_add_panelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_add_id_label)
                    .addComponent(id_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_add_name_label)
                    .addComponent(name_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menu_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_menu_add_label)
                    .addComponent(price_menu_add_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(menu_add_button)
                .addGap(39, 39, 39))
        );

        layered_pane.add(menu_add_panel, "card2");

        id_label_inventory_add_panel.setText("id:");

        name_label_inventory_add_panel.setText("name:");

        last_restock_date_label_inventory_add_panel.setText("last_restock_date:");

        amount_remaining_label_inventory_add_panel.setText("amount_remaining:");

        amount_used_label_inventory_add_panel.setText("amount_used:");

        add_inventory_item_button.setText("add inventory item");
        add_inventory_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_inventory_item_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventory_add_panelLayout = new javax.swing.GroupLayout(inventory_add_panel);
        inventory_add_panel.setLayout(inventory_add_panelLayout);
        inventory_add_panelLayout.setHorizontalGroup(
            inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_add_panelLayout.createSequentialGroup()
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventory_add_panelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(last_restock_date_label_inventory_add_panel)
                            .addGroup(inventory_add_panelLayout.createSequentialGroup()
                                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(inventory_add_panelLayout.createSequentialGroup()
                                            .addComponent(amount_remaining_label_inventory_add_panel)
                                            .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inventory_add_panelLayout.createSequentialGroup()
                                            .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(name_label_inventory_add_panel, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(id_label_inventory_add_panel, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(inventory_add_panelLayout.createSequentialGroup()
                                        .addComponent(amount_used_label_inventory_add_panel)
                                        .addGap(63, 63, 63)))
                                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_textField_inventory_add_panel)
                                    .addComponent(name_textField_inventory_add_panel)
                                    .addComponent(last_restock_date_textField_inventory_add_panel)
                                    .addComponent(amount_remaing_textField_inventory_add_panel)
                                    .addComponent(amount_used_textField_inventory_add_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))))
                    .addGroup(inventory_add_panelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(add_inventory_item_button)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        inventory_add_panelLayout.setVerticalGroup(
            inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_add_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_label_inventory_add_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label_inventory_add_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_restock_date_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_restock_date_label_inventory_add_panel))
                .addGap(18, 18, 18)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_remaining_label_inventory_add_panel)
                    .addComponent(amount_remaing_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventory_add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_used_textField_inventory_add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_used_label_inventory_add_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(add_inventory_item_button)
                .addGap(34, 34, 34))
        );

        layered_pane.add(inventory_add_panel, "card3");

        last_restock_inventory_date_label.setText("date_restocked:");

        last_restock_inventory_amount_label.setText("amount_restocked:");

        restockInventoryItem_button.setText("restock Inventory Item");
        restockInventoryItem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockInventoryItem_buttonActionPerformed(evt);
            }
        });

        id_last_restock_label.setText("id:");

        javax.swing.GroupLayout restock_inventory_item_panelLayout = new javax.swing.GroupLayout(restock_inventory_item_panel);
        restock_inventory_item_panel.setLayout(restock_inventory_item_panelLayout);
        restock_inventory_item_panelLayout.setHorizontalGroup(
            restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restock_inventory_item_panelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(restockInventoryItem_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restock_inventory_item_panelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last_restock_inventory_amount_label)
                    .addComponent(last_restock_inventory_date_label)
                    .addComponent(id_last_restock_label))
                .addGap(45, 45, 45)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_restock_inventory_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(last_restock_date_textField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_restock_inventory_amount_restocked_textField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        restock_inventory_item_panelLayout.setVerticalGroup(
            restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restock_inventory_item_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_restock_inventory_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_last_restock_label))
                .addGap(29, 29, 29)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_restock_date_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_restock_inventory_date_label))
                .addGap(18, 18, 18)
                .addGroup(restock_inventory_item_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_restock_inventory_amount_restocked_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_restock_inventory_amount_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(restockInventoryItem_button)
                .addGap(42, 42, 42))
        );

        layered_pane.add(restock_inventory_item_panel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layered_pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layered_pane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_buttonActionPerformed
        // TODO add your handling code here:
        if(!isNumber(id_menu_add_textField.getText()) || (name_menu_add_textField.getText().isBlank()) || !isNumber(price_menu_add_textField.getText())){
              throwErrorMessage();
        }else{
            if (database.addMenuItem(Integer.parseInt(id_menu_add_textField.getText()), name_menu_add_textField.getText(), Double.parseDouble(price_menu_add_textField.getText()))){
                throwSuccessMessage(1);
                id_menu_add_textField.setText("");
                name_menu_add_textField.setText("");
                price_menu_add_textField.setText("");
            
            }else{
                throwErrorMessage();
            }
        }
    }//GEN-LAST:event_menu_add_buttonActionPerformed

    private void add_inventory_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_inventory_item_buttonActionPerformed
        // TODO add your handling code here:
        if(!isNumber(id_textField_inventory_add_panel.getText())||(last_restock_date_textField_inventory_add_panel.getText().isBlank())||!isNumber(amount_remaing_textField_inventory_add_panel.getText()) || (name_textField_inventory_add_panel.getText().isBlank()) || !isNumber(amount_used_textField_inventory_add_panel.getText())){
              throwErrorMessage();
        }else{
            if (database.addInventoryItem(Integer.parseInt(id_textField_inventory_add_panel.getText()), name_textField_inventory_add_panel.getText(), last_restock_date_textField_inventory_add_panel.getText(),Integer.parseInt(amount_remaing_textField_inventory_add_panel.getText()),Integer.parseInt(amount_used_textField_inventory_add_panel.getText()))){
                throwSuccessMessage(1);
                id_textField_inventory_add_panel.setText("");
                name_textField_inventory_add_panel.setText("");
                last_restock_date_textField_inventory_add_panel.setText("");
                amount_remaing_textField_inventory_add_panel.setText("");
                amount_used_textField_inventory_add_panel.setText("");
            
            }else{
                throwErrorMessage();
            }
        }
    }//GEN-LAST:event_add_inventory_item_buttonActionPerformed

    private void restockInventoryItem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockInventoryItem_buttonActionPerformed
        // TODO add your handling code here:
        if (database.restockInventoryItem(Integer.parseInt(id_restock_inventory_textField.getText()), last_restock_date_textField.getText(), Integer.parseInt(last_restock_inventory_amount_restocked_textField.getText()))){
                throwSuccessMessage(1);
                id_restock_inventory_textField.setText("");
                last_restock_date_textField.setText("");
                last_restock_inventory_amount_restocked_textField.setText("");
            
            }else{
                throwErrorMessage();
            }
    }//GEN-LAST:event_restockInventoryItem_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dialogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dialogs().setVisible(true);
//            }
//        });
//    }
    public void switchDialogPanel(JPanel panel){
        layered_pane.removeAll();
        layered_pane.add(panel);
        layered_pane.repaint();
        layered_pane.revalidate();
    }
    public JPanel getInventoryAddPanel() {
        return inventory_add_panel;
    }
    public JPanel getMenuAddPanel() {
        return menu_add_panel;
    }
    public JPanel getRestockInventoryItemPanel() {
        return restock_inventory_item_panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_inventory_item_button;
    private javax.swing.JTextField amount_remaing_textField_inventory_add_panel;
    private javax.swing.JLabel amount_remaining_label_inventory_add_panel;
    private javax.swing.JLabel amount_used_label_inventory_add_panel;
    private javax.swing.JTextField amount_used_textField_inventory_add_panel;
    private javax.swing.JLabel id_label_inventory_add_panel;
    private javax.swing.JLabel id_last_restock_label;
    private javax.swing.JTextField id_menu_add_textField;
    private javax.swing.JTextField id_restock_inventory_textField;
    private javax.swing.JTextField id_textField_inventory_add_panel;
    private javax.swing.JPanel inventory_add_panel;
    private javax.swing.JLabel last_restock_date_label_inventory_add_panel;
    private javax.swing.JTextField last_restock_date_textField;
    private javax.swing.JTextField last_restock_date_textField_inventory_add_panel;
    private javax.swing.JLabel last_restock_inventory_amount_label;
    private javax.swing.JTextField last_restock_inventory_amount_restocked_textField;
    private javax.swing.JLabel last_restock_inventory_date_label;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JButton menu_add_button;
    private javax.swing.JLabel menu_add_id_label;
    private javax.swing.JLabel menu_add_name_label;
    private javax.swing.JPanel menu_add_panel;
    private javax.swing.JLabel name_label_inventory_add_panel;
    private javax.swing.JTextField name_menu_add_textField;
    private javax.swing.JTextField name_textField_inventory_add_panel;
    private javax.swing.JLabel price_menu_add_label;
    private javax.swing.JTextField price_menu_add_textField;
    private javax.swing.JButton restockInventoryItem_button;
    private javax.swing.JPanel restock_inventory_item_panel;
    // End of variables declaration//GEN-END:variables
}
