package com.mycompany.managergui;

import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ManagerPOS extends javax.swing.JFrame {

    /**
     * Creates new form ManagerPOS
     */
    
    Database database = new Database("csce315_971_arnav_sood", "arnav_sood");
    public ManagerPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employees_button = new javax.swing.JButton();
        sales_button = new javax.swing.JButton();
        inventory_button = new javax.swing.JButton();
        menu_button = new javax.swing.JButton();
        schedule_button = new javax.swing.JButton();
        layered_pane = new javax.swing.JLayeredPane();
        employees_panel = new javax.swing.JPanel();
        employees_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_table = new javax.swing.JTable();
        load_data_employee = new javax.swing.JButton();
        sales_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sales_table = new javax.swing.JTable();
        sales_label = new javax.swing.JLabel();
        load_data_sales = new javax.swing.JButton();
        menu_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        menu_table = new javax.swing.JTable();
        menu_label = new javax.swing.JLabel();
        load_data_menu = new javax.swing.JButton();
        add_menu_button = new javax.swing.JButton();
        id_label_menu_panel = new javax.swing.JLabel();
        name_label_menu_panel = new javax.swing.JLabel();
        price_label_menu_panel = new javax.swing.JLabel();
        id_textField_menu = new javax.swing.JTextField();
        name_textField_menu = new javax.swing.JTextField();
        price_textField_menu = new javax.swing.JTextField();
        delete_id_button_menu_panel = new javax.swing.JButton();
        update_name_button_menu_panel = new javax.swing.JButton();
        update_price_button_menu_panel = new javax.swing.JButton();
        inventory_panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inventory_table = new javax.swing.JTable();
        inventory_label = new javax.swing.JLabel();
        load_data_inventory = new javax.swing.JButton();
        add_inventory_button = new javax.swing.JButton();
        schedule_panel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        schedule_table = new javax.swing.JTable();
        schedule_label = new javax.swing.JLabel();
        load_data_schedule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager POS");
        setMaximumSize(new java.awt.Dimension(1150, 700));
        setMinimumSize(new java.awt.Dimension(1150, 700));

        employees_button.setText("Employees");
        employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees_buttonActionPerformed(evt);
            }
        });

        sales_button.setText("Sales");
        sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_buttonActionPerformed(evt);
            }
        });

        inventory_button.setText("Inventory");
        inventory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_buttonActionPerformed(evt);
            }
        });

        menu_button.setText("Menu");
        menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buttonActionPerformed(evt);
            }
        });

        schedule_button.setText("Schedule");
        schedule_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule_buttonActionPerformed(evt);
            }
        });

        layered_pane.setMaximumSize(new java.awt.Dimension(20000, 20000));
        layered_pane.setMinimumSize(new java.awt.Dimension(980, 650));
        layered_pane.setLayout(new java.awt.CardLayout());

        employees_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        employees_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        employees_panel.setPreferredSize(new java.awt.Dimension(980, 650));

        employees_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        employees_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employees_label.setText("Employees");
        employees_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        employees_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        employee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "username", "password", "name", "start_date", "salary", "position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employee_table.setPreferredSize(new java.awt.Dimension(300, 100));
        jScrollPane1.setViewportView(employee_table);

        load_data_employee.setText("Load Data");
        load_data_employee.setMaximumSize(new java.awt.Dimension(90, 25));
        load_data_employee.setMinimumSize(new java.awt.Dimension(90, 25));
        load_data_employee.setPreferredSize(new java.awt.Dimension(90, 25));
        load_data_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_data_employeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employees_panelLayout = new javax.swing.GroupLayout(employees_panel);
        employees_panel.setLayout(employees_panelLayout);
        employees_panelLayout.setHorizontalGroup(
            employees_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employees_panelLayout.createSequentialGroup()
                .addGroup(employees_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employees_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employees_label, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        employees_panelLayout.setVerticalGroup(
            employees_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employees_panelLayout.createSequentialGroup()
                .addGroup(employees_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employees_label)
                    .addGroup(employees_panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(load_data_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layered_pane.add(employees_panel, "card2");

        sales_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        sales_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        sales_panel.setPreferredSize(new java.awt.Dimension(980, 650));

        sales_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "price", "date_time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sales_table);

        sales_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        sales_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales_label.setText("Sales");
        sales_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sales_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        load_data_sales.setText("Load Data");
        load_data_sales.setMaximumSize(new java.awt.Dimension(90, 25));
        load_data_sales.setMinimumSize(new java.awt.Dimension(90, 25));
        load_data_sales.setPreferredSize(new java.awt.Dimension(90, 25));
        load_data_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_data_salesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sales_panelLayout = new javax.swing.GroupLayout(sales_panel);
        sales_panel.setLayout(sales_panelLayout);
        sales_panelLayout.setHorizontalGroup(
            sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_panelLayout.createSequentialGroup()
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sales_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sales_label, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        sales_panelLayout.setVerticalGroup(
            sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_panelLayout.createSequentialGroup()
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sales_label)
                    .addGroup(sales_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layered_pane.add(sales_panel, "card3");

        menu_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        menu_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        menu_panel.setPreferredSize(new java.awt.Dimension(980, 650));

        menu_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        menu_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(menu_table);

        menu_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        menu_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_label.setText("Menu");
        menu_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menu_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        load_data_menu.setText("Load Data");
        load_data_menu.setMaximumSize(new java.awt.Dimension(90, 25));
        load_data_menu.setMinimumSize(new java.awt.Dimension(90, 25));
        load_data_menu.setPreferredSize(new java.awt.Dimension(90, 25));
        load_data_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_data_menuActionPerformed(evt);
            }
        });

        add_menu_button.setText("Add");
        add_menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_menu_buttonActionPerformed(evt);
            }
        });

        id_label_menu_panel.setText("id");

        name_label_menu_panel.setText("name");

        price_label_menu_panel.setText("price");

        delete_id_button_menu_panel.setForeground(new java.awt.Color(255, 0, 0));
        delete_id_button_menu_panel.setText("delete item");
        delete_id_button_menu_panel.setActionCommand("Delete Item");
        delete_id_button_menu_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_id_button_menu_panelActionPerformed(evt);
            }
        });

        update_name_button_menu_panel.setText("update name");

        update_price_button_menu_panel.setText("update price");

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_textField_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_label_menu_panel)
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(delete_id_button_menu_panel)))
                .addGap(226, 226, 226)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_textField_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label_menu_panel)
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(update_name_button_menu_panel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_panelLayout.createSequentialGroup()
                        .addComponent(update_price_button_menu_panel)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_panelLayout.createSequentialGroup()
                        .addComponent(price_label_menu_panel)
                        .addGap(176, 176, 176))
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addComponent(price_textField_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(menu_label)
                        .addComponent(add_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(load_data_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label_menu_panel)
                    .addComponent(name_label_menu_panel)
                    .addComponent(price_label_menu_panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_textField_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_textField_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price_textField_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_id_button_menu_panel)
                    .addComponent(update_name_button_menu_panel)
                    .addComponent(update_price_button_menu_panel))
                .addContainerGap())
        );

        layered_pane.add(menu_panel, "card3");

        inventory_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        inventory_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        inventory_panel.setPreferredSize(new java.awt.Dimension(980, 650));

        inventory_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "last_restock_date", "amount_remaining", "amount_used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(inventory_table);

        inventory_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        inventory_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventory_label.setText("Inventory");
        inventory_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        inventory_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        load_data_inventory.setText("Load Data");
        load_data_inventory.setMaximumSize(new java.awt.Dimension(90, 25));
        load_data_inventory.setMinimumSize(new java.awt.Dimension(90, 25));
        load_data_inventory.setPreferredSize(new java.awt.Dimension(90, 25));
        load_data_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_data_inventoryActionPerformed(evt);
            }
        });

        add_inventory_button.setText("Add");
        add_inventory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_inventory_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventory_panelLayout = new javax.swing.GroupLayout(inventory_panel);
        inventory_panel.setLayout(inventory_panelLayout);
        inventory_panelLayout.setHorizontalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(load_data_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventory_label, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inventory_panelLayout.setVerticalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addGroup(inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inventory_label)
                        .addComponent(add_inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inventory_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layered_pane.add(inventory_panel, "card3");

        schedule_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        schedule_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        schedule_panel.setPreferredSize(new java.awt.Dimension(980, 650));

        schedule_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "shift_id", "employee_id", "month", "day_of_week"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(schedule_table);

        schedule_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        schedule_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schedule_label.setText("Schedule");
        schedule_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        schedule_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        load_data_schedule.setText("Load Data");
        load_data_schedule.setMaximumSize(new java.awt.Dimension(90, 25));
        load_data_schedule.setMinimumSize(new java.awt.Dimension(90, 25));
        load_data_schedule.setPreferredSize(new java.awt.Dimension(90, 25));
        load_data_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_data_scheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout schedule_panelLayout = new javax.swing.GroupLayout(schedule_panel);
        schedule_panel.setLayout(schedule_panelLayout);
        schedule_panelLayout.setHorizontalGroup(
            schedule_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedule_panelLayout.createSequentialGroup()
                .addGroup(schedule_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(schedule_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schedule_label, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        schedule_panelLayout.setVerticalGroup(
            schedule_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedule_panelLayout.createSequentialGroup()
                .addGroup(schedule_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schedule_label)
                    .addGroup(schedule_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(load_data_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        layered_pane.add(schedule_panel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employees_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sales_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventory_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schedule_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(layered_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(employees_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(schedule_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(layered_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void switchPanel(JPanel panel){
        layered_pane.removeAll();
        layered_pane.add(panel);
        layered_pane.repaint();
        layered_pane.revalidate();
    }
    public boolean isNumber(String str) {
    try {
        Double.parseDouble(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
    }
    
    public void throwErrorMessage(){
        Errors error = new Errors();
        error.setVisible(true);
        error.pack();
        error.setLocationRelativeTo(null);
        error.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        error.setTitle("ERROR Message");
    }
    public void throwSuccessMessage(){
        Successes success = new Successes();
        success.setVisible(true);
        success.pack();
        success.setLocationRelativeTo(null);
        success.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        success.setTitle("Success Message");
    }
    private void employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(employees_panel);
        
    }//GEN-LAST:event_employees_buttonActionPerformed

    private void sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(sales_panel);
    }//GEN-LAST:event_sales_buttonActionPerformed

    private void inventory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(inventory_panel);
    }//GEN-LAST:event_inventory_buttonActionPerformed

    private void menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(menu_panel);
    }//GEN-LAST:event_menu_buttonActionPerformed

    private void schedule_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(schedule_panel);
    }//GEN-LAST:event_schedule_buttonActionPerformed
    
    private void loadDataMenu(){
        DefaultTableModel tempModel = (DefaultTableModel)menu_table.getModel();
        tempModel.setRowCount(0);
        ResultSet menuData = database.getMenu();
        try{
            while(menuData.next()){
//                String id = String.valueOf(salesData.getInt("id"));
                String id = menuData.getString("id");
                String name = menuData.getString("name");
                String price = String.valueOf(menuData.getDouble("price"));
                String data[] = {id,name,price};
                DefaultTableModel model = (DefaultTableModel)menu_table.getModel();
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void load_data_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_data_employeeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tempModel = (DefaultTableModel)employee_table.getModel();
        tempModel.setRowCount(0);
        ResultSet employeeData = database.getEmployees();
        try{
            while(employeeData.next()){
                String id = employeeData.getString("id");
                String username = employeeData.getString("username");
                String password = employeeData.getString("password");
                String name = employeeData.getString("name");
                String start_date = employeeData.getString("start_date");
                String salary = String.valueOf(employeeData.getInt("salary"));
                String position = employeeData.getString("position");
                String data[] = {id,username,password,name,start_date,salary,position};
                DefaultTableModel model = (DefaultTableModel)employee_table.getModel();
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_load_data_employeeActionPerformed

    private void load_data_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_data_salesActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tempModel = (DefaultTableModel)sales_table.getModel();
        tempModel.setRowCount(0);
        ResultSet salesData = database.getAllOrders();
        try{
            while(salesData.next()){
//                String id = String.valueOf(salesData.getInt("id"));
                String id = salesData.getString("id");
                String price = salesData.getString("price");
//                String price = String.valueOf(salesData.getDouble("price"));
                String date_time = salesData.getString("date_time");
                String data[] = {id,price,date_time};
                DefaultTableModel model = (DefaultTableModel)sales_table.getModel();
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_load_data_salesActionPerformed

    private void load_data_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_data_inventoryActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tempModel = (DefaultTableModel)inventory_table.getModel();
        tempModel.setRowCount(0);
        ResultSet inventoryData = database.getInventory();
        try{
            while(inventoryData.next()){
                String id = String.valueOf(inventoryData.getInt("id"));
                String name = inventoryData.getString("name");
                String last_restock_date = inventoryData.getString("last_restock_date");
                String amount_remaining = String.valueOf(inventoryData.getInt("amount_remaining"));
                String amount_used = String.valueOf(inventoryData.getInt("amount_used"));
                String data[] = {id,name,last_restock_date,amount_remaining,amount_used};
                DefaultTableModel model = (DefaultTableModel)inventory_table.getModel();
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_load_data_inventoryActionPerformed

    private void load_data_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_data_menuActionPerformed
        // TODO add your handling code here:
        loadDataMenu();
    }//GEN-LAST:event_load_data_menuActionPerformed

    private void load_data_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_data_scheduleActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tempModel = (DefaultTableModel)schedule_table.getModel();
        tempModel.setRowCount(0);
        ResultSet scheduleData = database.getAllEmployeeShifts();
        try{
            while(scheduleData.next()){
                String id = String.valueOf(scheduleData.getInt("id"));
                String shift_id = String.valueOf(scheduleData.getInt("shift_id"));
                String employee_id = String.valueOf(scheduleData.getInt("employee_id"));
                String month = String.valueOf(scheduleData.getInt("month"));
                String day_of_week = scheduleData.getString("day_of_week");
                String data[] = {id,shift_id,employee_id,month,day_of_week};
                DefaultTableModel model = (DefaultTableModel)schedule_table.getModel();
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_load_data_scheduleActionPerformed

    private void add_menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_menu_buttonActionPerformed
        // TODO add your handling code here:
        Dialogs dialog = new Dialogs();
        dialog.switchDialogPanel(dialog.getMenuAddPanel());
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.pack();
        dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dialog.setTitle("Add Menu Item");
    }//GEN-LAST:event_add_menu_buttonActionPerformed

    private void add_inventory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_inventory_buttonActionPerformed
        // TODO add your handling code here:
        Dialogs dialog = new Dialogs();
        dialog.switchDialogPanel(dialog.getInventoryAddPanel());
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.pack();
        dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dialog.setTitle("Add Inventory Item");
    }//GEN-LAST:event_add_inventory_buttonActionPerformed

    private void menu_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)menu_table.getModel();
        int selected_row_index = menu_table.getSelectedRow();
        
        id_textField_menu.setText(model.getValueAt(selected_row_index,0).toString());
        name_textField_menu.setText(model.getValueAt(selected_row_index,1).toString());
        price_textField_menu.setText(model.getValueAt(selected_row_index,2).toString());
    }//GEN-LAST:event_menu_tableMouseClicked

    private void delete_id_button_menu_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_id_button_menu_panelActionPerformed
        // TODO add your handling code here:
        if(!isNumber(id_textField_menu.getText())||id_textField_menu.getText().isBlank()){
            throwErrorMessage();
        }else{
            if(database.deleteMenuItem(Integer.parseInt(id_textField_menu.getText()))){
                loadDataMenu();
                throwSuccessMessage();
                id_textField_menu.setText("");
                name_textField_menu.setText("");
                price_textField_menu.setText("");
            }else{
                throwErrorMessage();
            }
            
            
        }
    }//GEN-LAST:event_delete_id_button_menu_panelActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManagerPOS().setVisible(true);
//            }
//        });
////    new ManagerPOS().setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_inventory_button;
    private javax.swing.JButton add_menu_button;
    private javax.swing.JButton delete_id_button_menu_panel;
    private javax.swing.JTable employee_table;
    private javax.swing.JButton employees_button;
    private javax.swing.JLabel employees_label;
    private javax.swing.JPanel employees_panel;
    private javax.swing.JLabel id_label_menu_panel;
    private javax.swing.JTextField id_textField_menu;
    private javax.swing.JButton inventory_button;
    private javax.swing.JLabel inventory_label;
    private javax.swing.JPanel inventory_panel;
    private javax.swing.JTable inventory_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JButton load_data_employee;
    private javax.swing.JButton load_data_inventory;
    private javax.swing.JButton load_data_menu;
    private javax.swing.JButton load_data_sales;
    private javax.swing.JButton load_data_schedule;
    private javax.swing.JButton menu_button;
    private javax.swing.JLabel menu_label;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JTable menu_table;
    private javax.swing.JLabel name_label_menu_panel;
    private javax.swing.JTextField name_textField_menu;
    private javax.swing.JLabel price_label_menu_panel;
    private javax.swing.JTextField price_textField_menu;
    private javax.swing.JButton sales_button;
    private javax.swing.JLabel sales_label;
    private javax.swing.JPanel sales_panel;
    private javax.swing.JTable sales_table;
    private javax.swing.JButton schedule_button;
    private javax.swing.JLabel schedule_label;
    private javax.swing.JPanel schedule_panel;
    private javax.swing.JTable schedule_table;
    private javax.swing.JButton update_name_button_menu_panel;
    private javax.swing.JButton update_price_button_menu_panel;
    // End of variables declaration//GEN-END:variables
}
