package com.mycompany.managergui;

import javax.swing.*;

public class ManagerPOS extends javax.swing.JFrame {

    /**
     * Creates new form ManagerPOS
     */
    public ManagerPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employees_button = new javax.swing.JButton();
        sales_button = new javax.swing.JButton();
        inventory_button = new javax.swing.JButton();
        menu_button = new javax.swing.JButton();
        schedule_button = new javax.swing.JButton();
        layered_pane = new javax.swing.JLayeredPane();
        employees_panel = new javax.swing.JPanel();
        employees_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_table = new javax.swing.JTable();
        sales_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sales_table = new javax.swing.JTable();
        sales_label = new javax.swing.JLabel();
        menu_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        menu_table = new javax.swing.JTable();
        menu_label = new javax.swing.JLabel();
        inventory_panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inventory_table = new javax.swing.JTable();
        inventory_label = new javax.swing.JLabel();
        schedule_panel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        schedule_table = new javax.swing.JTable();
        schedule_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager POS");
        setMaximumSize(new java.awt.Dimension(1150, 700));
        setMinimumSize(new java.awt.Dimension(1150, 700));
        setPreferredSize(new java.awt.Dimension(1150, 700));

        employees_button.setText("Employees");
        employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees_buttonActionPerformed(evt);
            }
        });

        sales_button.setText("Sales");
        sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_buttonActionPerformed(evt);
            }
        });

        inventory_button.setText("Inventory");
        inventory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_buttonActionPerformed(evt);
            }
        });

        menu_button.setText("Menu");
        menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buttonActionPerformed(evt);
            }
        });

        schedule_button.setText("Schedule");
        schedule_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule_buttonActionPerformed(evt);
            }
        });

        layered_pane.setMaximumSize(new java.awt.Dimension(20000, 20000));
        layered_pane.setMinimumSize(new java.awt.Dimension(980, 650));
        layered_pane.setPreferredSize(new java.awt.Dimension(980, 650));
        layered_pane.setLayout(new java.awt.CardLayout());

        employees_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        employees_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        employees_panel.setPreferredSize(new java.awt.Dimension(980, 650));
        employees_panel.setLayout(new java.awt.BorderLayout());

        employees_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        employees_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employees_label.setText("Employees");
        employees_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        employees_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        employees_panel.add(employees_label, java.awt.BorderLayout.NORTH);

        employee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        employee_table.setPreferredSize(new java.awt.Dimension(300, 100));
        jScrollPane1.setViewportView(employee_table);

        employees_panel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        layered_pane.add(employees_panel, "card2");

        sales_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        sales_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        sales_panel.setPreferredSize(new java.awt.Dimension(980, 650));
        sales_panel.setLayout(new java.awt.BorderLayout());

        sales_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sales_table);

        sales_panel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        sales_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        sales_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales_label.setText("Sales");
        sales_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sales_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        sales_panel.add(sales_label, java.awt.BorderLayout.NORTH);

        layered_pane.add(sales_panel, "card3");

        menu_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        menu_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        menu_panel.setPreferredSize(new java.awt.Dimension(980, 650));
        menu_panel.setLayout(new java.awt.BorderLayout());

        menu_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(menu_table);

        menu_panel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        menu_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        menu_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_label.setText("Menu");
        menu_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menu_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menu_panel.add(menu_label, java.awt.BorderLayout.NORTH);

        layered_pane.add(menu_panel, "card3");

        inventory_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        inventory_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        inventory_panel.setPreferredSize(new java.awt.Dimension(980, 650));
        inventory_panel.setLayout(new java.awt.BorderLayout());

        inventory_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(inventory_table);

        inventory_panel.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        inventory_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        inventory_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventory_label.setText("Inventory");
        inventory_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        inventory_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        inventory_panel.add(inventory_label, java.awt.BorderLayout.NORTH);

        layered_pane.add(inventory_panel, "card3");

        schedule_panel.setMaximumSize(new java.awt.Dimension(20000, 20000));
        schedule_panel.setMinimumSize(new java.awt.Dimension(980, 650));
        schedule_panel.setPreferredSize(new java.awt.Dimension(980, 650));
        schedule_panel.setLayout(new java.awt.BorderLayout());

        schedule_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(schedule_table);

        schedule_panel.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        schedule_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        schedule_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schedule_label.setText("Schedule");
        schedule_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        schedule_label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        schedule_panel.add(schedule_label, java.awt.BorderLayout.NORTH);

        layered_pane.add(schedule_panel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employees_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sales_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventory_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schedule_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(layered_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(employees_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(schedule_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(layered_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void switchPanel(JPanel panel){
        layered_pane.removeAll();
        layered_pane.add(panel);
        layered_pane.repaint();
        layered_pane.revalidate();
    }
    private void employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(employees_panel);
        
    }//GEN-LAST:event_employees_buttonActionPerformed

    private void sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(sales_panel);
    }//GEN-LAST:event_sales_buttonActionPerformed

    private void inventory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(inventory_panel);
    }//GEN-LAST:event_inventory_buttonActionPerformed

    private void menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(menu_panel);
    }//GEN-LAST:event_menu_buttonActionPerformed

    private void schedule_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule_buttonActionPerformed
        // TODO add your handling code here:
        switchPanel(schedule_panel);
    }//GEN-LAST:event_schedule_buttonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerPOS().setVisible(true);
            }
        });
//    new ManagerPOS().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable employee_table;
    private javax.swing.JButton employees_button;
    private javax.swing.JLabel employees_label;
    private javax.swing.JPanel employees_panel;
    private javax.swing.JButton inventory_button;
    private javax.swing.JLabel inventory_label;
    private javax.swing.JPanel inventory_panel;
    private javax.swing.JTable inventory_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JButton menu_button;
    private javax.swing.JLabel menu_label;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JTable menu_table;
    private javax.swing.JButton sales_button;
    private javax.swing.JLabel sales_label;
    private javax.swing.JPanel sales_panel;
    private javax.swing.JTable sales_table;
    private javax.swing.JButton schedule_button;
    private javax.swing.JLabel schedule_label;
    private javax.swing.JPanel schedule_panel;
    private javax.swing.JTable schedule_table;
    // End of variables declaration//GEN-END:variables
}
