package cashierpos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Spencer Logan
 */
public class OrderMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OrderMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu_item_3 = new javax.swing.JButton();
        menu_item_4 = new javax.swing.JButton();
        menu_item_5 = new javax.swing.JButton();
        menu_item_6 = new javax.swing.JButton();
        menu_item_7 = new javax.swing.JButton();
        menu_item_9 = new javax.swing.JButton();
        menu_item_11 = new javax.swing.JButton();
        menu_item_13 = new javax.swing.JButton();
        menu_item_15 = new javax.swing.JButton();
        menu_item_17 = new javax.swing.JButton();
        menu_item_1 = new javax.swing.JButton();
        menu_item_19 = new javax.swing.JButton();
        menu_item_2 = new javax.swing.JButton();
        menu_item_8 = new javax.swing.JButton();
        menu_item_10 = new javax.swing.JButton();
        menu_item_12 = new javax.swing.JButton();
        menu_item_14 = new javax.swing.JButton();
        menu_item_16 = new javax.swing.JButton();
        menu_item_18 = new javax.swing.JButton();
        menu_item_20 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_text = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        subtotal_text = new javax.swing.JTextField();
        tax_text = new javax.swing.JTextField();
        total_text = new javax.swing.JTextField();
        checkout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 86)); // NOI18N
        jLabel1.setText("Menu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 86)); // NOI18N
        jLabel2.setText("Order");

        menu_item_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_3.setText("BS Deer Milk");
        menu_item_3.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_3ActionPerformed(evt);
            }
        });

        menu_item_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_4.setText("Peach Oo Tea");
        menu_item_4.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_4ActionPerformed(evt);
            }
        });

        menu_item_5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_5.setText("Jas Gr Tea");
        menu_item_5.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_5ActionPerformed(evt);
            }
        });

        menu_item_6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_6.setText("Snow Vel Roy 9");
        menu_item_6.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_6ActionPerformed(evt);
            }
        });

        menu_item_7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_7.setText("Roy 9 Milk Tea");
        menu_item_7.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_7ActionPerformed(evt);
            }
        });

        menu_item_9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_9.setText("Alley Trio");
        menu_item_9.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_9ActionPerformed(evt);
            }
        });

        menu_item_11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_11.setText("Pass Fr Gr Tea");
        menu_item_11.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_11ActionPerformed(evt);
            }
        });

        menu_item_13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_13.setText("Matcha Purp Yog");
        menu_item_13.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_13ActionPerformed(evt);
            }
        });

        menu_item_15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_15.setText("Taro Milk Tea");
        menu_item_15.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_15ActionPerformed(evt);
            }
        });

        menu_item_17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_17.setText("Mango Frappe");
        menu_item_17.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_17ActionPerformed(evt);
            }
        });

        menu_item_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_1.setText("Mango LuLu");
        menu_item_1.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_1ActionPerformed(evt);
            }
        });

        menu_item_19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_19.setText("Milk Tea Cold Brew");
        menu_item_19.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_19ActionPerformed(evt);
            }
        });

        menu_item_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_2.setText("Strawb LuLu");
        menu_item_2.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_2ActionPerformed(evt);
            }
        });

        menu_item_8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_8.setText("Alley Milk Tea");
        menu_item_8.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_8ActionPerformed(evt);
            }
        });

        menu_item_10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_10.setText("Lychee Gr Tea");
        menu_item_10.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_10ActionPerformed(evt);
            }
        });

        menu_item_12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_12.setText("Yog Purp Rice");
        menu_item_12.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_12ActionPerformed(evt);
            }
        });

        menu_item_14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_14.setText("Peach Oo Purp Rice");
        menu_item_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_14ActionPerformed(evt);
            }
        });

        menu_item_16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_16.setText("Taro Smoothie");
        menu_item_16.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_16ActionPerformed(evt);
            }
        });

        menu_item_18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_18.setText("CCream Cold Brew");
        menu_item_18.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_18ActionPerformed(evt);
            }
        });

        menu_item_20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_20.setText("Orange LuLu");
        menu_item_20.setMinimumSize(new java.awt.Dimension(122, 21));
        menu_item_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_20ActionPerformed(evt);
            }
        });

        order_text.setColumns(20);
        order_text.setRows(5);
        jScrollPane1.setViewportView(order_text);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Subtotal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Tax");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Total");

        subtotal_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subtotal_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subtotal_text.setText("$0.00");
        subtotal_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotal_textActionPerformed(evt);
            }
        });

        tax_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tax_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tax_text.setText("$0.00");

        total_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_text.setText("$0.00");

        checkout_button.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        checkout_button.setText("Checkout");
        checkout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtotal_text)
                                    .addComponent(total_text)
                                    .addComponent(tax_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(menu_item_15, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menu_item_16, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(menu_item_19, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menu_item_20, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(menu_item_17, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menu_item_18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_item_11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_item_12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_item_9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_item_10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_item_7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_item_8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_item_13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_item_14, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menu_item_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu_item_5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu_item_4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_item_1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_item_2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menu_item_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu_item_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_item_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_item_10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_item_19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_item_20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(subtotal_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tax_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(total_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(checkout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_3ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_3ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_4ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_4ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_5ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_5ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_6ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_6ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_7ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_7ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_9ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_9ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_11ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_11ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_13ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_13ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_15ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_15ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_17ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_17ActionPerformed
    /**
     * Creates add on menu for this menu item
     * @param evt button click event
     * @return void
     */
    private void menu_item_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_1ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_1ActionPerformed
    
    private void subtotal_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotal_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotal_textActionPerformed

    private void menu_item_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_2ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_2ActionPerformed

    private void menu_item_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_8ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_8ActionPerformed

    private void menu_item_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_10ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_10ActionPerformed

    private void menu_item_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_12ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_12ActionPerformed

    private void menu_item_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_14ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_14ActionPerformed

    private void menu_item_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_16ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_16ActionPerformed

    private void menu_item_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_18ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_18ActionPerformed

    private void menu_item_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_19ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_19ActionPerformed

    private void menu_item_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_20ActionPerformed
        new AddOnMenu().setVisible(true);
    }//GEN-LAST:event_menu_item_20ActionPerformed

    private void checkout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkout_buttonActionPerformed
        order_text.setText("");
    }//GEN-LAST:event_checkout_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkout_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu_item_1;
    private javax.swing.JButton menu_item_10;
    private javax.swing.JButton menu_item_11;
    private javax.swing.JButton menu_item_12;
    private javax.swing.JButton menu_item_13;
    private javax.swing.JButton menu_item_14;
    private javax.swing.JButton menu_item_15;
    private javax.swing.JButton menu_item_16;
    private javax.swing.JButton menu_item_17;
    private javax.swing.JButton menu_item_18;
    private javax.swing.JButton menu_item_19;
    private javax.swing.JButton menu_item_2;
    private javax.swing.JButton menu_item_20;
    private javax.swing.JButton menu_item_3;
    private javax.swing.JButton menu_item_4;
    private javax.swing.JButton menu_item_5;
    private javax.swing.JButton menu_item_6;
    private javax.swing.JButton menu_item_7;
    private javax.swing.JButton menu_item_8;
    private javax.swing.JButton menu_item_9;
    private javax.swing.JTextArea order_text;
    private javax.swing.JTextField subtotal_text;
    private javax.swing.JTextField tax_text;
    private javax.swing.JTextField total_text;
    // End of variables declaration//GEN-END:variables
}
